---
title: "Accessing CMIP6 ESM data"
author: "Denisse Fierro Arcos"
date: "2022-10-24"
output: 
  github_document:
    toc: true
    html_preview: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction
In this notebook, we will use `R` to calculate monthly means for the data downloaded in the previous step [01_Accessing_CMIP6_data](01_Accessing_CMIP6_data.md).


```{r cars}
summary(cars)
```



## Calculating monthly means per decade
For this portion of the script, we will switch back to `R`. We will calculate monthly means per decade and save them locally.
```{r}
for(i in 1:nrow(results_query)){
  #Loading raster
  r <- nc_open(results_query$out_path[i])
  #Accessing variable of interest
  var <- ncvar_get(r, results_query$variable_id[i])
  #Accessing coordinates - notice these are 2D arrays
  lon <- ncvar_get(r, "lon")
  lat <- ncvar_get(r, "lat")
  #Creating 1D index for coordinates for easy plotting
  #longitude coordinates formatted -180 to +180
  x <- ifelse(lon[,1,1] > 180, lon[,1,1]-360, lon[,1,1])
  y <- lat[1,,1]
  #Accessing time dimension 
  time <- ncvar_get(r, "time")
  #Reordering variables along x axis for easy plotting
  var <- var[order(x),,]
  lon <- lon[order(x),,]
  x <- x[order(x)]
  
  #Getting years where decade 0 and decade N start from
  dec0 <- results_query$decade_0_start[i]
  decN <- results_query$decade_N_start[i]
  
  #Converting time from integers to dates
  #Extracting date time origin
  origin <- str_extract(ncatt_get(r, "time", "units")$value, "\\d{4}-\\d{2}-\\d{2}")
  #Saving converted dates into tibble
  ds_dates <- time %>% 
    as_tibble() %>% 
    #Adding column ID for easy reference
    rowid_to_column("id") %>% 
    #Adding month, year and decade
    mutate(time = as_date(value, origin = origin),
           year = year(time),
           month = month(time),
           #First decade classified as 1, final decade identified as 2
           dec = case_when(year <= results_query$decade_0_end[i] ~ 1,
                           T ~ 2)) %>% 
    #Removing original time values
    select(-value)
  
  #Calculating monthly means per decade
  for(d in unique(ds_dates$dec)){
    month_mean <- list()
    for(m in 1:12){
      #Slicing dataset per month/decade
      #Identifying indices
      ind <- ds_dates %>% 
        filter(dec == d & month == m) %>% 
        select(id) %>% 
        pull()
      #Calculating monthly means and reordering for easy plotting
      month_mean[[m]] <- apply(var[,,ind], 1:2, mean, na.rm = T)
    }
    #Creating a single file per decade
    dec_month_mean <- array(unlist(month_mean), dim = c(length(x), length(y), 12))
    
    #Creating netcdf
    #Adding lat and lon coordinates as indexes
    xdim <- ncdim_def("x", "degrees_east", x)
    ydim <- ncdim_def("y", "degrees_north", y)
    #Adding time dimension
    timedim <- ncdim_def("month", "month of the year", 1:12)
    #Adding monthly mean
    clim_ds <- ncvar_def("monthly_mean", ncatt_get(r, results_query$variable_id[i])$units,
                         list(xdim, ydim, timedim), 
                         ncatt_get(r, results_query$variable_id[i])$missing_value,
                         paste0("Monthly mean ",
                                ncatt_get(r, results_query$variable_id[i])$long_name))
    #Adding lat and lon as separate dimension
    lon_ds <- ncvar_def("lon", ncatt_get(r, "lon")$units,
                         list(xdim, ydim, timedim), ncatt_get(r, "lon")$missing_value,
                         ncatt_get(r, "lon")$long_name)
    lat_ds <- ncvar_def("lat", ncatt_get(r, "lat")$units,
                         list(xdim, ydim, timedim), ncatt_get(r, "lat")$missing_value,
                         ncatt_get(r, "lat")$long_name)
    #Copying global attributes from original file
    global_atts <- ncatt_get(r, 0)
    
    
    #Naming monthly mean files per decade
    if(d == 1){
      dec_start <- dec0
    }else{dec_start <- decN}
    #Creating file name
    file_name <- paste0(results_query$base_file_name[i], ".MonthlyMean.", 
                        dec_start, "-", (dec_start+9), ".nc")
    #Creating full path
    file_out <- file.path(results_query$out_full_folder[i], file_name)
    
    #Putting everything together in one file
    ncout <- nc_create(file_out, list(clim_ds, lon_ds, lat_ds), force_v4 = T)
    ncvar_put(ncout, clim_ds, dec_month_mean)
    ncvar_put(ncout, lon_ds, lon[,,1:12])
    ncvar_put(ncout, lat_ds, lat[,,1:12])
    for(j in 1:length(global_atts)){
      ncatt_put(ncout, 0, names(global_atts)[j], global_atts[[j]])
    }
    
    #Closing the file so it is saved on disk
    nc_close(ncout)
  }
  nc_close(r)
}

```

